[package]
name = "drawing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color = "0.3.2"
image = "0.25.9"
rand = "0.9.2"
raster = "0.2.0"
rgb = "0.8.52"
rng = "0.1.0"
